apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-config
  namespace: monitoring
data:
  loki.yaml: |
    auth_enabled: false
    server:
      http_listen_port: 3100
    ingester:
      chunk_target_size: 1048576
      max_chunk_age: 1h
    retention:
      # Set retention policy to 2 days
      enabled: true
      max_age: 48h
    storage_config:
      boltdb_shipper:
        active_index_directory: /data/loki/index
        cache_location: /data/loki/cache
        cache_ttl: 24h
      filesystem:
        directory: /data/loki/chunks
    schema_config:
      configs:
        - from: 2020-10-15
          store: boltdb_shipper
          object_store: filesystem
          schema: v11
          index:
            prefix: loki_index_
            period: 168h
