apiVersion: apps/v1
kind: Deployment
metadata:
  name: tempo
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tempo
  template:
    metadata:
      labels:
        app: tempo
    spec:
      containers:
        - name: tempo
          image: grafana/tempo:2.0.0
          ports:
            - containerPort: 3200
          volumeMounts:
            - name: tempo-config
              mountPath: /etc/tempo
      volumes:
        - name: tempo-config
          configMap:
            name: tempo-config

---
apiVersion: v1
kind: Service
metadata:
  name: tempo-service
  namespace: monitoring
spec:
  ports:
    - port: 3200
      targetPort: 3200
  selector:
    app: tempo
