apiVersion: v1
kind: ConfigMap
metadata:
  name: tempo-config
  namespace: monitoring
data:
  tempo.yaml: |
    server:
      http_listen_port: 3200
    storage:
      trace:
        backend: "memcached"
        memcached:
          address: "localhost:11211"
    api:
      disable_grpc: false
    retention:
      max_age: 48h
